### ISSUE TITLE
Save some bytes

### ISSUE THREAD

**Issue by mnot** [diracdeltas/FastestWebsiteEver#1]
>   hdrbytes = sprintf(send_buffer, "HTTP/1.1 200 OK\r\nContent-Length: %d\r\ncontent-encoding: deflate\r\n\r\n", numbytes);

* Clients should accept just `\n` for line termination, so you can shave off 4 `\r`s
* The reason-phrase isn't checked, so you should be able to get away with a single byte here, maybe even zero. Try `O`.

**Comment by diracdeltas** [comment]
@mnot thanks for this very urgent issue. we are on it.

**Comment by mnot** [comment]
4% bigger payload = more sweet ad 💰.
